import sys


def read_stdin_col(col_num):
    """
    Purpose
    -------
    This function takes a column of numbers, generated by
    get_data.sh, as input from standard in and returns an
    array of the numbers in the column.

    Inputs
    ------
    col_num: integer
    Column to take from standard in.

    Outputs
    -------
    column: array
    Array whose values are the numbers in the column taken as input.
    """

    column_in = sys.stdin.read()

    column = []
    for column_line in column_in:
        try:
            column_number = column_line.rstrip().split(' ')
            column.append(int(column_number))
        except ValueError:
            print('Standardin input must be only integers')
            sys.exit(1)
        except IndexError:
            print('Selected column number is not in standardin')
            sys.exit(1)

    return column


def main():

    stdin_column = read_stdin_col()
    return stdin_column


if __name__ == '__main__':
    main()
